name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'v16.20.2'

      - name: Install pnpm and pm2
        run: |
          npm install -g pnpm
          npm install -g pm2

      - name: Install dependencies
        run: pnpm install

      - name: Run linting
        run: pnpm run lint

      - name: Run tests
        run: pnpm run test

      - name: Build proyect
        run: pnpm build

      # - name: Deploy to server
      #   run: ssh root@landings-staging.clientify.net "ls"
        # ssh root@landings-staging.clientify.net "pm2 stop test"
        # ssh root@landings-staging.clientify.net "cd test-deploy-continuos && git pull"
        # ssh root@landings-staging.clientify.net "cd test-deploy-continuos && nest build"
        # ssh root@landings-staging.clientify.net "pm2 start test"


      # - name: ADD github.com AS A KNOWN HOST
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.SSH_PRIVATE_KEY_TEST }}" > ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa
      #     echo "************************"
      #     cat ~/.ssh/id_rsa
      #     echo "************************"
      #     ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

    #  - name: Install SSH Key
      #  uses: shimataro/ssh-key-action@v2
      #  with:
        #  key: $\{{ secrets.SSH_PRIVATE_KEY_TEST }}
        #  known_hosts: unnecessary

    #  - name: Adding Known Hosts
      #  run: ssh-keyscan -p $\{{ secrets.SSH_PORT}} -H $\{{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts
      #  run: ssh-keyscan -p 22 -H landings-staging.clientify.net  >> ~/.ssh/known_hosts

      - name: Configurar Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git config --global credential.helper store

      # - name: Obtener token de acceso personal
      #   run: echo "${{ secrets.TOKEN_TEST }}" > token.txt

      # - name: Realizar pull de la rama main
      #   run: |
      #     export GITHUB_TOKEN=$(cat token.txt)
      #     git pull origin main

      # - name: Eliminar token de acceso personal
      #   run: rm token.txt

      - name: Deploy server
        uses: appleboy/ssh-action@master
        with:
          host: "landings-staging.clientify.net"
          username: "root"
          key: ${{ secrets.SSH_PRIVATE_KEY_TEST }}
          script: |
            whoami
            cd ~/test-deploy-continuos
            pm2 stop test
            export TOKEN_TEST=$(cat token.txt)
            git pull origin main
            pnpm install
            pnpm run build
            pm2 start test

